name: Deploy to VM
on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Docker login
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build push image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: anazbinnoushad/cabi-server:${{ github.sha }}

            - name: Deploy to the EC2
              run: |
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
                  chmod 600 ~/ssh_key
                  ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.55.206.71 -t "
                    echo '${{ secrets.DOCKERHUB_TOKEN }}' | sudo docker login -u '${{ secrets.DOCKERHUB_USERNAME }}' --password-stdin
                    sudo docker pull anazbinnoushad/cabi-server:${{ github.sha }}
                    sudo docker stop cabi-server || true
                    sudo docker rm cabi-server || true
                    sudo docker run --name cabi-server -d \
                    --restart unless-stopped \
                    --env-file /home/ubuntu/.env \
                    -p 3000:3000 \
                    -v cabi-server-data:/app/data \
                    anazbinnoushad/cabi-server:${{ github.sha }}
                  "
